import Link from "next/link";
import { ArrowUpRight, BarChart3, Check, MessageCircle, ShieldCheck, Sparkles } from "lucide-react";
import { AgencyPlanInterestForm } from "@/components/agency/AgencyPlanInterestForm";
import { AgencyCheckoutButton } from "@/components/agency/AgencyCheckoutButton";

const plans = [
  { code: "STARTER", name: "Starter", featured: false, price: "499 MAD", note: "Pour lancer une présence professionnelle", features: ["Profil agence vérifié", "Jusqu’à 10 biens", "Réception des leads", "Support de démarrage"] },
  { code: "PRO", name: "Pro", price: "1 500 MAD", note: "Pour les équipes qui veulent accélérer", featured: true, features: ["Jusqu’à 50 biens", "CRM et pipeline leads", "Messagerie propriétaires", "Statistiques et alertes", "WhatsApp concierge"] },
  { code: "PREMIUM", name: "Premium", featured: false, price: "4 000 MAD", note: "Pour les agences à forte activité", features: ["Biens mis en avant", "Rapports propriétaires", "Équipe multi-agents", "SLA de réponse", "Accompagnement prioritaire"] },
  { code: null, name: "Entreprise", featured: false, price: "Sur mesure", note: "Pour réseaux et promoteurs", features: ["Portefeuilles multi-agences", "Intégrations personnalisées", "Marque blanche", "Onboarding dédié", "Reporting direction"] },
] as const;

export default function PricingPage() {
  return <main className="min-h-screen bg-[radial-gradient(circle_at_85%_0%,rgba(232,203,145,0.14),transparent_24rem)] bg-[#faf9f6] pb-20"><section className="relative overflow-hidden border-b border-white/10 bg-domify-primary-dark py-20 text-white sm:py-28"><div className="pointer-events-none absolute -right-28 -top-28 h-96 w-96 rounded-full border border-domify-soft-gold/20" /><div className="relative mx-auto max-w-6xl px-4 sm:px-6 lg:px-8"><p className="luxury-eyebrow text-domify-soft-gold">Solutions professionnelles</p><h1 className="mt-5 max-w-3xl font-display text-4xl font-semibold leading-[1.04] sm:text-7xl">Donnez à votre agence une avance plus élégante.</h1><p className="mt-5 max-w-2xl text-base leading-8 text-white/68">Domify réunit visibilité premium, CRM, messagerie, suivi des propriétaires et pilotage commercial dans un même espace immobilier.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#offres" className="pressable inline-flex items-center gap-2 rounded-full bg-domify-gold px-5 py-3 text-sm font-semibold text-white hover:bg-domify-soft-gold hover:text-domify-primary-dark">Voir les offres <ArrowUpRight size={16} /></a><Link href="/contact" className="pressable inline-flex items-center gap-2 rounded-full border border-white/20 px-5 py-3 text-sm font-semibold text-white hover:bg-white/10"><MessageCircle size={16} /> Parler à Domify</Link></div></div></section>

    <section id="offres" className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{plans.map((plan) => <article key={plan.name} className={`relative rounded-[1.65rem] border p-7 shadow-[0_24px_54px_-36px_rgba(16,47,66,0.58)] ${plan.featured ? "border-domify-gold bg-domify-primary-dark text-white" : "border-domify-dark/8 bg-white text-domify-dark"}`}>{plan.featured && <span className="absolute right-5 top-5 rounded-full bg-domify-gold px-2.5 py-1 text-[0.65rem] font-bold uppercase tracking-wider text-white">Le plus choisi</span>}<p className={`luxury-eyebrow ${plan.featured ? "text-domify-soft-gold" : "text-domify-gold"}`}>{plan.name}</p><p className="mt-5 font-display text-3xl font-semibold">{plan.price}<span className={`text-sm font-sans font-normal ${plan.featured ? "text-white/50" : "text-domify-dark/45"}`}>{plan.price.includes("Sur") ? "" : " / mois"}</span></p><p className={`mt-3 min-h-10 text-sm leading-6 ${plan.featured ? "text-white/65" : "text-domify-dark/55"}`}>{plan.note}</p><ul className="mt-6 space-y-3">{plan.features.map((feature) => <li key={feature} className="flex items-start gap-2 text-sm"><Check className={`mt-0.5 shrink-0 ${plan.featured ? "text-domify-soft-gold" : "text-domify-gold"}`} size={16} /><span>{feature}</span></li>)}</ul>{plan.code ? <AgencyCheckoutButton plan={plan.code} featured={plan.featured} /> : <a href="#demande" className={`mt-8 inline-flex w-full items-center justify-center rounded-xl px-4 py-3 text-sm font-semibold ${plan.featured ? "bg-domify-gold text-white hover:bg-domify-soft-gold hover:text-domify-primary-dark" : "bg-domify-warm-white text-domify-primary hover:bg-domify-gold/10"}`}>Demander une présentation</a>}</article>)}</div></section>

    <section className="mx-auto grid max-w-7xl gap-6 px-4 sm:px-6 lg:grid-cols-[0.9fr_1.1fr] lg:px-8"><div className="rounded-[1.7rem] border border-domify-dark/6 bg-domify-warm-white p-7 shadow-[0_18px_40px_-32px_rgba(16,47,66,0.32)] sm:p-9"><p className="luxury-eyebrow text-domify-gold">Pourquoi Domify</p><h2 className="mt-3 font-display text-3xl font-semibold text-domify-dark">Plus qu’une vitrine, un système de confiance.</h2><div className="mt-7 space-y-5"><Benefit icon={ShieldCheck} title="Validation et qualité" text="Vos annonces, vos médias et vos informations suivent un parcours de contrôle clair." /><Benefit icon={BarChart3} title="Décisions mesurables" text="Suivez les demandes, les visites, les délais de réponse et les résultats par équipe." /><Benefit icon={Sparkles} title="Expérience premium" text="Présentez vos biens avec une interface cohérente, rapide et pensée pour les projets importants." /></div></div><div id="demande" className="rounded-[1.7rem] border border-domify-dark/8 bg-white/95 p-7 shadow-[0_24px_50px_-34px_rgba(16,47,66,0.42)] sm:p-9"><p className="luxury-eyebrow text-domify-gold">Devenir partenaire</p><h2 className="mt-3 font-display text-3xl font-semibold text-domify-dark">Demander une présentation</h2><p className="mt-3 mb-6 text-sm leading-6 text-domify-dark/55">Choisissez une offre indicative. Un conseiller vous présentera les conditions adaptées à votre portefeuille et à vos objectifs.</p><AgencyPlanInterestForm /></div></section>
  </main>;
}

function Benefit({ icon: Icon, title, text }: { icon: typeof ShieldCheck; title: string; text: string }) { return <div className="flex gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white text-domify-gold shadow-sm"><Icon size={18} /></span><div><h3 className="font-semibold text-domify-dark">{title}</h3><p className="mt-1 text-sm leading-6 text-domify-dark/55">{text}</p></div></div>; }
