export type MortgageRateProfile = {
  slug: string;
  name: string;
  nominalRatePercent: number;
  tegPercent: number;
  sourceReferenceRatePercent: number | null;
  monthlyPaymentMad: number | null;
  confidence: "medium" | "low";
  brandColor: string;
  brandColorLight: string;
  logoPath: string;
};

export const MORTGAGE_RATES_LAST_VERIFIED = "20 avril 2026";
export const MORTGAGE_RATES_SOURCE_LABEL = "Comparatif indicatif Crédit.ma";
export const MORTGAGE_RATES_SOURCE_URL = "https://credit.ma/comparer?type=mortgage&montant=500000&duree=20&profil=salarie";
export const MORTGAGE_RATES_MARKET_SOURCE_URL = "https://medias24.com/2026/06/09/credit-immobilier-des-taux-a-4-mais-des-ecarts-importants-selon-les-profils-1695745/";

export const MORTGAGE_BANK_RATES: MortgageRateProfile[] = [
  {
    slug: "market-average",
    name: "Moyenne du marché — Afdal",
    nominalRatePercent: 4.64,
    tegPercent: 5.49,
    sourceReferenceRatePercent: null,
    monthlyPaymentMad: null,
    confidence: "medium",
    brandColor: "#163B57",
    brandColorLight: "#EDF5F8",
    logoPath: "/banks/market-average.svg",
  },
  {
    slug: "bank-of-africa",
    name: "Bank of Africa",
    nominalRatePercent: 4.5,
    tegPercent: 5.38,
    sourceReferenceRatePercent: 4.35,
    monthlyPaymentMad: 3163,
    confidence: "medium",
    brandColor: "#ED7A23",
    brandColorLight: "#FFF1E7",
    logoPath: "/banks/bank-of-africa.svg",
  },
  {
    slug: "bmci",
    name: "BMCI",
    nominalRatePercent: 4.6,
    tegPercent: 5.49,
    sourceReferenceRatePercent: 4.4,
    monthlyPaymentMad: 3190,
    confidence: "medium",
    brandColor: "#00884A",
    brandColorLight: "#E8F6EF",
    logoPath: "/banks/bmci.svg",
  },
  {
    slug: "attijariwafa-bank",
    name: "Attijariwafa bank",
    nominalRatePercent: 4.75,
    tegPercent: 5.66,
    sourceReferenceRatePercent: 4.15,
    monthlyPaymentMad: 3231,
    confidence: "medium",
    brandColor: "#F06445",
    brandColorLight: "#FFF0EB",
    logoPath: "/banks/attijariwafa-bank.svg",
  },
  {
    slug: "cih-bank",
    name: "CIH Bank",
    nominalRatePercent: 4.75,
    tegPercent: 5.66,
    sourceReferenceRatePercent: 4.1,
    monthlyPaymentMad: 3231,
    confidence: "medium",
    brandColor: "#0F5DAA",
    brandColorLight: "#EAF4FE",
    logoPath: "/banks/cih-bank.svg",
  },
  {
    slug: "credit-du-maroc",
    name: "Crédit du Maroc",
    nominalRatePercent: 4.75,
    tegPercent: 5.66,
    sourceReferenceRatePercent: 4.3,
    monthlyPaymentMad: 3231,
    confidence: "medium",
    brandColor: "#007A5E",
    brandColorLight: "#E7F6F0",
    logoPath: "/banks/credit-du-maroc.svg",
  },
  {
    slug: "banque-populaire",
    name: "Banque Populaire / BCP",
    nominalRatePercent: 4.9,
    tegPercent: 5.82,
    sourceReferenceRatePercent: 4.15,
    monthlyPaymentMad: 3272,
    confidence: "medium",
    brandColor: "#1677BC",
    brandColorLight: "#EAF5FC",
    logoPath: "/banks/banque-populaire.svg",
  },
  {
    slug: "saham-bank",
    name: "Saham Bank",
    nominalRatePercent: 4.9,
    tegPercent: 5.82,
    sourceReferenceRatePercent: 4.3,
    monthlyPaymentMad: 3272,
    confidence: "medium",
    brandColor: "#D4462E",
    brandColorLight: "#FFF0EC",
    logoPath: "/banks/saham-bank.svg",
  },
  {
    slug: "cfg-bank",
    name: "CFG Bank",
    nominalRatePercent: 4.9,
    tegPercent: 5.82,
    sourceReferenceRatePercent: null,
    monthlyPaymentMad: 3272,
    confidence: "low",
    brandColor: "#D45443",
    brandColorLight: "#FFF0ED",
    logoPath: "/banks/cfg-bank.svg",
  },
  {
    slug: "umnia-bank",
    name: "Umnia Bank",
    nominalRatePercent: 5.1,
    tegPercent: 6.04,
    sourceReferenceRatePercent: 4.6,
    monthlyPaymentMad: 3327,
    confidence: "medium",
    brandColor: "#8F1248",
    brandColorLight: "#FCECF3",
    logoPath: "/banks/umnia-bank.svg",
  },
  {
    slug: "bank-assafa",
    name: "Bank Assafa",
    nominalRatePercent: 5.2,
    tegPercent: 6.15,
    sourceReferenceRatePercent: 4.8,
    monthlyPaymentMad: 3355,
    confidence: "medium",
    brandColor: "#00916E",
    brandColorLight: "#EAF8F3",
    logoPath: "/banks/bank-assafa.svg",
  },
  {
    slug: "al-akhdar-bank",
    name: "Al Akhdar Bank",
    nominalRatePercent: 5.3,
    tegPercent: 6.26,
    sourceReferenceRatePercent: 4.9,
    monthlyPaymentMad: 3383,
    confidence: "medium",
    brandColor: "#4E8D3A",
    brandColorLight: "#EFF7EA",
    logoPath: "/banks/al-akhdar-bank.svg",
  },
  {
    slug: "bank-al-karam",
    name: "Bank Al Karam",
    nominalRatePercent: 5.4,
    tegPercent: 6.37,
    sourceReferenceRatePercent: 5,
    monthlyPaymentMad: 3411,
    confidence: "medium",
    brandColor: "#8A1E37",
    brandColorLight: "#FAEDF1",
    logoPath: "/banks/bank-al-karam.svg",
  },
];
