import Link from "next/link";
import { ArrowRight, BadgeCheck, BellRing, CheckCircle2, ClipboardCheck, FileCheck2, Gauge, Languages, MapPinned, ShieldAlert, Timer, UserRoundCheck } from "lucide-react";
import { redirect } from "next/navigation";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { assessListingQuality } from "@/lib/property-quality";
import { AdminTopbar } from "@/components/admin/AdminTopbar";

function format(value: number) { return new Intl.NumberFormat("fr-MA").format(value); }

export default async function OperationsPage() {
  const session = await auth();
  if (session?.user?.role !== "ADMIN") redirect("/admin");

  const now = new Date();
  const [properties, overdueContacts, assignmentRules, documents, reports, searches, localeGapCount, neighborhoods, deliveryFailures] = await Promise.all([
    prisma.property.findMany({
      where: { status: "PUBLISHED" },
      select: { id: true, title: true, description: true, titleEn: true, titleAr: true, descriptionEn: true, descriptionAr: true, price: true, surfaceArea: true, bedrooms: true, bathrooms: true, address: true, city: { select: { name: true } }, neighborhood: { select: { name: true } }, _count: { select: { media: true, amenities: true } } },
      orderBy: { updatedAt: "desc" },
    }),
    prisma.crmContact.findMany({ where: { slaDueAt: { lt: now }, firstRespondedAt: null }, select: { id: true, name: true, email: true, slaDueAt: true, owner: { select: { name: true } } }, orderBy: { slaDueAt: "asc" }, take: 8 }),
    prisma.crmAssignmentRule.findMany({ where: { active: true }, select: { id: true, name: true, priority: true, assignee: { select: { name: true } } }, orderBy: { priority: "asc" } }),
    prisma.crmDocument.findMany({ where: { status: { in: ["REQUESTED", "UPLOADED", "REJECTED"] } }, select: { id: true, name: true, status: true, requestedAt: true, rejectedReason: true, contact: { select: { name: true } }, property: { select: { title: true } } }, orderBy: { createdAt: "desc" }, take: 8 }),
    prisma.ownerReport.findMany({ where: { status: { in: ["DRAFT", "FAILED"] } }, select: { id: true, status: true, periodEnd: true, property: { select: { title: true } }, contact: { select: { name: true } } }, orderBy: { createdAt: "desc" }, take: 8 }),
    prisma.crmSavedSearch.groupBy({ by: ["channel"], where: { active: true }, _count: { _all: true } }),
    prisma.property.count({ where: { status: "PUBLISHED", OR: [{ titleAr: null }, { descriptionAr: null }, { titleEn: null }, { descriptionEn: null }] } }),
    prisma.neighborhood.findMany({ select: { id: true, name: true, description: true, _count: { select: { properties: { where: { status: "PUBLISHED" } } } } }, orderBy: { name: "asc" } }),
    prisma.auditLog.count({ where: { action: { contains: "FAILED" }, createdAt: { gte: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000) } } }),
  ]);

  const quality = properties.map((property) => ({ property, quality: assessListingQuality({ ...property, cityName: property.city.name, neighborhoodName: property.neighborhood?.name, mediaCount: property._count.media, amenityCount: property._count.amenities }) }));
  const qualityIssues = quality.filter((item) => item.quality.level !== "ready").sort((a, b) => a.quality.score - b.quality.score);
  const averageQuality = quality.length ? Math.round(quality.reduce((sum, item) => sum + item.quality.score, 0) / quality.length) : 0;
  const neighborhoodsWithoutContext = neighborhoods.filter((neighborhood) => !neighborhood.description || neighborhood._count.properties === 0);
  const activeSearches = searches.reduce((sum, item) => sum + item._count._all, 0);

  return <>
    <AdminTopbar title="Centre des opérations" />
    <main className="admin-page-shell min-w-0 p-4 sm:p-6 lg:p-10">
      <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="admin-eyebrow">Qualité, confiance et continuité</p><h1 className="font-display text-3xl font-bold text-domify-dark dark:text-white">Centre des opérations</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-domify-dark/60 dark:text-white/60">Une lecture priorisée de la qualité catalogue, des délais de réponse, des documents, des rapports propriétaires, des alertes acheteurs, des traductions et des signaux de santé.</p></div><Link href="/admin/lancement" className="inline-flex w-fit items-center gap-2 rounded-full border border-domify-primary/15 bg-white px-4 py-2.5 text-sm font-semibold text-domify-primary shadow-sm transition hover:border-domify-gold hover:text-domify-gold dark:bg-white/10 dark:text-domify-soft-gold">Contrôle de lancement <ArrowRight size={15} /></Link></header>

      <section className="mt-8 grid grid-cols-2 gap-3 xl:grid-cols-5"><Metric icon={<BadgeCheck size={18} />} label="Qualité moyenne" value={`${averageQuality}/100`} tone={averageQuality >= 80 ? "good" : "warn"} href="/admin/properties" /><Metric icon={<Timer size={18} />} label="SLA échus" value={format(overdueContacts.length)} tone={overdueContacts.length ? "bad" : "good"} href="/admin/leads" /><Metric icon={<FileCheck2 size={18} />} label="Documents à traiter" value={format(documents.length)} tone={documents.length ? "warn" : "good"} href="/admin/crm" /><Metric icon={<BellRing size={18} />} label="Alertes actives" value={format(activeSearches)} href="/admin/crm/operations" /><Metric icon={<Languages size={18} />} label="Fiches à localiser" value={format(localeGapCount)} tone={localeGapCount ? "warn" : "good"} href="/admin/properties" /></section>

      <div className="mt-8 grid gap-6 xl:grid-cols-2"><Panel icon={<BadgeCheck size={18} />} title="Qualité des annonces" description="Les premières améliorations à apporter avant de renforcer la visibilité d’une annonce." href="/admin/properties" empty="Toutes les annonces publiées dépassent le seuil de qualité.">{qualityIssues.slice(0, 6).map(({ property, quality: result }) => <QueueRow key={property.id} title={property.title} detail={`${result.score}/100 · ${result.missing.slice(0, 2).join(" · ") || "À finaliser"}`} badge={result.level === "incomplete" ? "Priorité" : "À améliorer"} tone={result.level === "incomplete" ? "bad" : "warn"} href={`/admin/properties/${property.id}`} />)}</Panel>
        <Panel icon={<Timer size={18} />} title="Leads et attribution" description="Les contacts sans première réponse après leur délai cible doivent être repris ou réattribués." href="/admin/leads" empty="Aucun SLA en dépassement.">{overdueContacts.map((contact) => <QueueRow key={contact.id} title={contact.name} detail={`${contact.email} · échéance ${contact.slaDueAt?.toLocaleString("fr-MA") ?? "—"} · ${contact.owner?.name ?? "non attribué"}`} badge="À traiter" tone="bad" href={`/admin/crm/contacts/${contact.id}`} />)}<div className="mt-4 rounded-xl bg-domify-warm-white p-3 text-xs text-domify-dark/60 dark:bg-white/5 dark:text-white/60"><b className="text-domify-dark dark:text-white">Règles actives :</b> {assignmentRules.length ? assignmentRules.map((rule) => `${rule.name} → ${rule.assignee.name}`).join(" · ") : "aucune règle active"}</div></Panel></div>

      <div className="mt-6 grid gap-6 xl:grid-cols-3"><Panel icon={<FileCheck2 size={18} />} title="Vérification documentaire" description="Demandes, fichiers reçus et refus nécessitant une décision ou une relance." href="/admin/crm" empty="Aucun document en attente.">{documents.map((document) => <QueueRow key={document.id} title={document.name} detail={`${document.contact?.name ?? "Contact"} · ${document.property?.title ?? "Dossier CRM"}${document.rejectedReason ? ` · ${document.rejectedReason}` : ""}`} badge={document.status} tone={document.status === "REJECTED" ? "bad" : "warn"} href="/admin/crm" />)}</Panel>
        <Panel icon={<UserRoundCheck size={18} />} title="Rapports propriétaires" description="Rapports à finaliser ou à relancer pour assurer une visibilité continue aux vendeurs." href="/espace-vendeur" empty="Tous les rapports sont prêts ou envoyés.">{reports.map((report) => <QueueRow key={report.id} title={report.property?.title ?? "Rapport propriétaire"} detail={`${report.contact.name} · période terminée le ${report.periodEnd.toLocaleDateString("fr-MA")}`} badge={report.status} tone={report.status === "FAILED" ? "bad" : "warn"} href="/admin/crm" />)}</Panel>
        <Panel icon={<MapPinned size={18} />} title="Intelligence des quartiers" description="Les quartiers avec peu de contexte ou sans annonce publiée sont à enrichir avant les campagnes." href="/admin/neighborhoods" empty="Tous les quartiers disposent d’un contexte et d’annonces publiées.">{neighborhoodsWithoutContext.slice(0, 6).map((neighborhood) => <QueueRow key={neighborhood.id} title={neighborhood.name} detail={`${neighborhood.description ? "Contexte présent" : "Description à compléter"} · ${neighborhood._count.properties} bien(s) publié(s)`} badge="À enrichir" tone="warn" href="/admin/neighborhoods" />)}</Panel></div>

      <section className="mt-6 grid gap-6 xl:grid-cols-2"><Panel icon={<Languages size={18} />} title="Couverture de localisation" description="Les fiches sans titres ou descriptions EN/AR restent visibles dans la langue source. Corrigez-les avant leur promotion internationale." href="/admin/properties" empty="La couverture de traduction des fiches publiées est complète."><QueueRow title={`${localeGapCount} fiche(s) à compléter`} detail="Titres ou descriptions anglais/arabe manquants sur des annonces publiées." badge={localeGapCount ? "À localiser" : "Prêt"} tone={localeGapCount ? "warn" : "good"} href="/admin/properties" /></Panel>
        <Panel icon={<Gauge size={18} />} title="Santé opérationnelle" description="Signaux disponibles sans exposer de secret : échecs audités de la semaine et raccourcis de supervision." href="/admin/lancement" empty="Aucun échec audité récent."><QueueRow title={`${deliveryFailures} échec(s) audité(s) sur 7 jours`} detail="Consultez le journal d’audit, l’historique e-mail et le contrôle de lancement pour les détails." badge={deliveryFailures ? "À examiner" : "Stable"} tone={deliveryFailures ? "bad" : "good"} href="/admin/audit-log" /><div className="mt-4 grid grid-cols-2 gap-2"><QuickLink href="/admin/analytics" label="Analytique" icon={<Gauge size={14} />} /><QuickLink href="/admin/lancement" label="Santé système" icon={<CheckCircle2 size={14} />} /><QuickLink href="/admin/settings" label="Intégrations" icon={<ShieldAlert size={14} />} /><QuickLink href="/admin/crm/operations" label="Automatisations" icon={<ClipboardCheck size={14} />} /></div></Panel></section>
    </main>
  </>;
}

function Metric({ icon, label, value, tone = "normal", href }: { icon: React.ReactNode; label: string; value: string; tone?: "normal" | "good" | "warn" | "bad"; href: string }) { const colors = tone === "bad" ? "text-rose-700 bg-rose-50" : tone === "warn" ? "text-amber-700 bg-amber-50" : tone === "good" ? "text-emerald-700 bg-emerald-50" : "text-domify-primary bg-domify-warm-white"; return <Link href={href} className="rounded-2xl bg-white p-4 shadow-luxury transition hover:-translate-y-0.5 dark:bg-[#102436] sm:p-5"><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${colors}`}>{icon}</span><p className="mt-4 font-display text-2xl font-bold text-domify-dark dark:text-white">{value}</p><p className="mt-1 text-xs text-domify-dark/55 dark:text-white/55">{label}</p></Link>; }
function Panel({ icon, title, description, href, empty, children }: { icon: React.ReactNode; title: string; description: string; href: string; empty: string; children: React.ReactNode }) { const items = Array.isArray(children) ? children.filter(Boolean) : [children].filter(Boolean); return <section className="rounded-2xl bg-white p-4 shadow-luxury dark:bg-[#102436] sm:p-6"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-domify-gold">{icon}<h2 className="font-display text-lg font-semibold text-domify-dark dark:text-white">{title}</h2></div><p className="mt-2 text-xs leading-5 text-domify-dark/55 dark:text-white/55">{description}</p></div><Link href={href} className="shrink-0 text-domify-primary dark:text-domify-soft-gold"><ArrowRight size={16} /></Link></div><div className="mt-5 space-y-2">{items.length ? children : <p className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">{empty}</p>}</div></section>; }
function QueueRow({ title, detail, badge, tone, href }: { title: string; detail: string; badge: string; tone: "good" | "warn" | "bad"; href: string }) { const color = tone === "bad" ? "bg-rose-50 text-rose-700" : tone === "warn" ? "bg-amber-50 text-amber-700" : "bg-emerald-50 text-emerald-700"; return <Link href={href} className="block rounded-xl border border-domify-dark/7 p-3 transition hover:border-domify-gold/45 hover:bg-domify-warm-white dark:border-white/10 dark:hover:bg-white/5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold text-domify-dark dark:text-white">{title}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-domify-dark/55 dark:text-white/55">{detail}</p></div><span className={`shrink-0 rounded-full px-2 py-1 text-[10px] font-bold ${color}`}>{badge}</span></div></Link>; }
function QuickLink({ href, label, icon }: { href: string; label: string; icon: React.ReactNode }) { return <Link href={href} className="flex items-center gap-2 rounded-lg bg-domify-warm-white px-3 py-2 text-xs font-semibold text-domify-primary transition hover:bg-domify-gold/15 dark:bg-white/5 dark:text-domify-soft-gold">{icon}{label}</Link>; }
