export type SampleListing = {
  reference: string;
  slug: string;
  city: string;
  cityId: string;
  neighborhoodId?: string;
  propertyType: string;
  propertyTypeId: string;
  listingType: "VENTE" | "LOCATION";
  status: "PUBLISHED";
  price: number;
  surfaceArea: number;
  bedrooms: number;
  bathrooms: number;
  floors: number;
  yearBuilt: number;
  featured: boolean;
  address: string;
  latitude: number;
  longitude: number;
  amenityIds: string[];
  imageUrls: string[];
  title: string;
  titleEn: string;
  titleAr: string;
  description: string;
  descriptionEn: string;
  descriptionAr: string;
  seoTitle: string;
  seoTitleEn: string;
  seoTitleAr: string;
  seoDescription: string;
  seoDescriptionEn: string;
  seoDescriptionAr: string;
};

const amenities = {
  airConditioning: "cmscgde0m000aucvibq7a7f9i",
  homeAutomation: "cmscgddfu0009ucvi1nn2u1dc",
  twoCarGarage: "cmscgdczp0008ucvirlm59hcf",
  privateGarden: "cmscgdcjj0007ucvitpkjzgxb",
  swimmingPool: "cmscgdc3b0006ucvi7taz5k3g",
  fitnessRoom: "cmscgdf0t000cucviv5qn8bqb",
  security: "cmscgdeki000bucvig7rmr5rs",
  seaView: "cmscgdfh4000ducvit5x77itp",
} as const;

export const sampleListings: SampleListing[] = [
  {
    reference: "DEMO-CAS-001",
    slug: "demo-appartement-signature-racine-casablanca",
    city: "Casablanca",
    cityId: "cmscgdfxh000eucvi74nsd2vt",
    neighborhoodId: "cmscgdjpw000mucvi5bivyil6",
    propertyType: "Appartement",
    propertyTypeId: "cmscgd9dc0000ucvip12rahjw",
    listingType: "VENTE",
    status: "PUBLISHED",
    price: 2850000,
    surfaceArea: 148,
    bedrooms: 3,
    bathrooms: 2,
    floors: 8,
    yearBuilt: 2022,
    featured: true,
    address: "Racine, Casablanca — localisation illustrative",
    latitude: 33.5882,
    longitude: -7.6406,
    amenityIds: [amenities.airConditioning, amenities.homeAutomation, amenities.fitnessRoom, amenities.security],
    imageUrls: ["/sample-listings/casablanca-loft.jpg"],
    title: "Annonce exemple — Appartement signature à Racine",
    titleEn: "Sample listing — Signature apartment in Racine",
    titleAr: "عقار نموذجي — شقة مميزة في راسين",
    description: "Appartement lumineux imaginé pour illustrer une résidence contemporaine à Racine, avec séjour ouvert, trois chambres et finitions soignées. Les informations, le prix et la localisation sont fournis uniquement à titre d’exemple : ce bien n’est pas disponible pour une transaction réelle.",
    descriptionEn: "A bright apartment created to illustrate a contemporary Racine residence, with an open living space, three bedrooms, and refined finishes. The facts, price, and location are illustrative only; this sample property is not available for a real transaction.",
    descriptionAr: "شقة مشرقة صُممت لتوضيح نموذج إقامة عصرية في راسين، وتضم مساحة معيشة مفتوحة وثلاث غرف نوم وتشطيبات أنيقة. البيانات والسعر والموقع معلومات إرشادية فقط، وهذا العقار النموذجي غير متاح لمعاملة حقيقية.",
    seoTitle: "Annonce exemple — Appartement à Racine, Casablanca | Domify",
    seoTitleEn: "Sample listing — Apartment in Racine, Casablanca | Domify",
    seoTitleAr: "عقار نموذجي — شقة في راسين، الدار البيضاء | دوميفاي",
    seoDescription: "Annonce exemple Domify : appartement illustratif à Racine. Prix, visuels et localisation non contractuels et non disponibles à la transaction.",
    seoDescriptionEn: "Domify sample listing: illustrative Racine apartment. Price, imagery, and location are non-contractual and unavailable for a transaction.",
    seoDescriptionAr: "عقار نموذجي من دوميفاي: شقة توضيحية في راسين. السعر والصور والموقع غير تعاقدية وليست متاحة للمعاملات.",
  },
  {
    reference: "DEMO-CAS-002",
    slug: "demo-location-appartement-maarif-casablanca",
    city: "Casablanca",
    cityId: "cmscgdfxh000eucvi74nsd2vt",
    neighborhoodId: "cmscgdk62000nucvi8uek25nt",
    propertyType: "Appartement",
    propertyTypeId: "cmscgd9dc0000ucvip12rahjw",
    listingType: "LOCATION",
    status: "PUBLISHED",
    price: 17500,
    surfaceArea: 98,
    bedrooms: 2,
    bathrooms: 2,
    floors: 6,
    yearBuilt: 2021,
    featured: false,
    address: "Maarif, Casablanca — localisation illustrative",
    latitude: 33.584,
    longitude: -7.6355,
    amenityIds: [amenities.airConditioning, amenities.homeAutomation, amenities.fitnessRoom, amenities.security],
    imageUrls: ["/sample-listings/casablanca-city.jpg"],
    title: "Annonce exemple — Appartement urbain au Maarif",
    titleEn: "Sample listing — Urban apartment in Maarif",
    titleAr: "عقار نموذجي — شقة عصرية في المعاريف",
    description: "Cet appartement urbain est une fiche de démonstration destinée à présenter la location longue durée à Casablanca, entre lignes contemporaines et confort quotidien. Tous les éléments affichés, y compris le loyer et l’emplacement, sont illustratifs et ce bien n’est pas réellement disponible.",
    descriptionEn: "This urban apartment is a demonstration listing for long-term rental in Casablanca, combining contemporary lines with everyday comfort. Every displayed element, including rent and location, is illustrative, and the property is not actually available.",
    descriptionAr: "هذه الشقة العصرية صفحة عرض توضيحية لاستئجار طويل الأمد في الدار البيضاء، تجمع بين التصميم المعاصر والراحة اليومية. جميع التفاصيل المعروضة، بما فيها الإيجار والموقع، إرشادية فقط والعقار غير متاح فعلياً.",
    seoTitle: "Annonce exemple — Location au Maarif, Casablanca | Domify",
    seoTitleEn: "Sample listing — Rental in Maarif, Casablanca | Domify",
    seoTitleAr: "عقار نموذجي — إيجار في المعاريف، الدار البيضاء | دوميفاي",
    seoDescription: "Annonce exemple Domify pour une location illustrative au Maarif. Loyer, photos et emplacement sont fictifs et non transactionnels.",
    seoDescriptionEn: "Domify sample listing for an illustrative Maarif rental. Rent, photos, and location are fictional and non-transactional.",
    seoDescriptionAr: "عقار نموذجي من دوميفاي لإيجار توضيحي في المعاريف. الإيجار والصور والموقع افتراضية وغير مخصصة للمعاملات.",
  },
  {
    reference: "DEMO-CAS-003",
    slug: "demo-villa-jardin-bouskoura",
    city: "Bouskoura",
    cityId: "cmscgdhqa000iucvizcy5jp8i",
    propertyType: "Villa",
    propertyTypeId: "cmscgd9tz0001ucvizi1yanz5",
    listingType: "VENTE",
    status: "PUBLISHED",
    price: 6900000,
    surfaceArea: 420,
    bedrooms: 4,
    bathrooms: 4,
    floors: 2,
    yearBuilt: 2020,
    featured: false,
    address: "Bouskoura Ville Verte — localisation illustrative",
    latitude: 33.4675,
    longitude: -7.657,
    amenityIds: [amenities.airConditioning, amenities.twoCarGarage, amenities.privateGarden, amenities.swimmingPool, amenities.security],
    imageUrls: ["/sample-listings/casablanca-villa.jpg"],
    title: "Annonce exemple — Villa jardin à Bouskoura",
    titleEn: "Sample listing — Garden villa in Bouskoura",
    titleAr: "عقار نموذجي — فيلا بحديقة في بوسكورة",
    description: "Villa familiale de démonstration inspirée des résidences verdoyantes de Bouskoura, avec jardin, piscine et espaces de réception généreux. Il s’agit d’un contenu illustratif : les caractéristiques, coordonnées et prix n’ont aucune valeur d’offre immobilière réelle.",
    descriptionEn: "A demonstration family villa inspired by Bouskoura’s leafy residences, with garden, pool, and generous entertaining spaces. This is illustrative content: its features, coordinates, and price do not constitute a real property offer.",
    descriptionAr: "فيلا عائلية توضيحية مستوحاة من الإقامات الخضراء في بوسكورة، مع حديقة ومسبح ومساحات واسعة للاستقبال. هذا محتوى إرشادي فقط، والمواصفات والإحداثيات والسعر لا تشكل عرضاً عقارياً حقيقياً.",
    seoTitle: "Annonce exemple — Villa à Bouskoura | Domify",
    seoTitleEn: "Sample listing — Villa in Bouskoura | Domify",
    seoTitleAr: "عقار نموذجي — فيلا في بوسكورة | دوميفاي",
    seoDescription: "Annonce exemple Domify : villa illustrative à Bouskoura. Prix, visuels et localisation ne correspondent pas à une offre réelle.",
    seoDescriptionEn: "Domify sample listing: illustrative Bouskoura villa. Price, imagery, and location do not represent a real offer.",
    seoDescriptionAr: "عقار نموذجي من دوميفاي: فيلا توضيحية في بوسكورة. السعر والصور والموقع لا تمثل عرضاً حقيقياً.",
  },
  {
    reference: "DEMO-RAB-001",
    slug: "demo-appartement-residence-hay-riad-rabat",
    city: "Rabat",
    cityId: "cmscgdgdj000fucvilv9waknl",
    neighborhoodId: "cmscgdj9o000lucvigea0g2j4",
    propertyType: "Appartement",
    propertyTypeId: "cmscgd9dc0000ucvip12rahjw",
    listingType: "VENTE",
    status: "PUBLISHED",
    price: 3650000,
    surfaceArea: 185,
    bedrooms: 3,
    bathrooms: 3,
    floors: 7,
    yearBuilt: 2023,
    featured: true,
    address: "Hay Riad, Rabat — localisation illustrative",
    latitude: 33.9616,
    longitude: -6.864,
    amenityIds: [amenities.airConditioning, amenities.homeAutomation, amenities.fitnessRoom, amenities.security],
    imageUrls: ["/sample-listings/rabat-residence.jpg"],
    title: "Annonce exemple — Appartement familial à Hay Riad",
    titleEn: "Sample listing — Family apartment in Hay Riad",
    titleAr: "عقار نموذجي — شقة عائلية في حي الرياض",
    description: "Cet appartement familial de démonstration met en scène le confort d’une résidence récente à Hay Riad, avec terrasse, trois suites et services partagés. Les données affichées sont exclusivement illustratives et ne correspondent pas à un bien à vendre.",
    descriptionEn: "This demonstration family apartment illustrates the comfort of a recent Hay Riad residence, with terrace, three suites, and shared services. All displayed data is illustrative only and does not correspond to a property for sale.",
    descriptionAr: "هذه الشقة العائلية النموذجية تعرض راحة إقامة حديثة في حي الرياض، مع شرفة وثلاث غرف وأماكن مشتركة. جميع البيانات المعروضة إرشادية فقط ولا تخص عقاراً معروضاً للبيع.",
    seoTitle: "Annonce exemple — Appartement à Hay Riad, Rabat | Domify",
    seoTitleEn: "Sample listing — Apartment in Hay Riad, Rabat | Domify",
    seoTitleAr: "عقار نموذجي — شقة في حي الرياض، الرباط | دوميفاي",
    seoDescription: "Annonce exemple Domify : appartement illustratif à Hay Riad. Ce contenu, son prix et sa localisation ne sont pas une offre réelle.",
    seoDescriptionEn: "Domify sample listing: illustrative Hay Riad apartment. This content, its price, and location are not a real offer.",
    seoDescriptionAr: "عقار نموذجي من دوميفاي: شقة توضيحية في حي الرياض. المحتوى والسعر والموقع لا يمثلون عرضاً حقيقياً.",
  },
  {
    reference: "DEMO-RAB-002",
    slug: "demo-villa-contemporaine-souissi-rabat",
    city: "Rabat",
    cityId: "cmscgdgdj000fucvilv9waknl",
    neighborhoodId: "cmscgditj000kucvi3ebml33h",
    propertyType: "Villa",
    propertyTypeId: "cmscgd9tz0001ucvizi1yanz5",
    listingType: "VENTE",
    status: "PUBLISHED",
    price: 8400000,
    surfaceArea: 610,
    bedrooms: 5,
    bathrooms: 5,
    floors: 2,
    yearBuilt: 2019,
    featured: true,
    address: "Souissi, Rabat — localisation illustrative",
    latitude: 33.9858,
    longitude: -6.8156,
    amenityIds: [amenities.airConditioning, amenities.twoCarGarage, amenities.privateGarden, amenities.swimmingPool, amenities.security],
    imageUrls: ["/sample-listings/rabat-villa.jpg"],
    title: "Annonce exemple — Villa contemporaine à Souissi",
    titleEn: "Sample listing — Contemporary villa in Souissi",
    titleAr: "عقار نموذجي — فيلا عصرية في السويسي",
    description: "Villa contemporaine créée comme support de démonstration pour les parcours premium Domify, avec cinq chambres, jardin privé et piscine. Les vues, le prix, l’adresse et les informations techniques sont fictifs, illustratifs et indisponibles à la transaction.",
    descriptionEn: "A contemporary villa created as a demonstration for Domify’s premium journeys, with five bedrooms, private garden, and pool. Views, price, address, and technical information are fictional, illustrative, and unavailable for a transaction.",
    descriptionAr: "فيلا عصرية أُنشئت كنموذج لرحلات دوميفاي المميزة، وتضم خمس غرف نوم وحديقة خاصة ومسبحاً. المشاهد والسعر والعنوان والمعلومات التقنية افتراضية وإرشادية وغير متاحة للمعاملات.",
    seoTitle: "Annonce exemple — Villa à Souissi, Rabat | Domify",
    seoTitleEn: "Sample listing — Villa in Souissi, Rabat | Domify",
    seoTitleAr: "عقار نموذجي — فيلا في السويسي، الرباط | دوميفاي",
    seoDescription: "Annonce exemple Domify : villa illustrative à Souissi. Les informations affichées ne constituent pas une offre de vente réelle.",
    seoDescriptionEn: "Domify sample listing: illustrative Souissi villa. Displayed information does not constitute a real sale offer.",
    seoDescriptionAr: "عقار نموذجي من دوميفاي: فيلا توضيحية في السويسي. المعلومات المعروضة لا تشكل عرض بيع حقيقياً.",
  },
  {
    reference: "DEMO-RAB-003",
    slug: "demo-duplex-location-hay-riad-rabat",
    city: "Rabat",
    cityId: "cmscgdgdj000fucvilv9waknl",
    neighborhoodId: "cmscgdj9o000lucvigea0g2j4",
    propertyType: "Duplex",
    propertyTypeId: "cmscgdaa70002ucvi7u1bz0fr",
    listingType: "LOCATION",
    status: "PUBLISHED",
    price: 24000,
    surfaceArea: 215,
    bedrooms: 4,
    bathrooms: 3,
    floors: 10,
    yearBuilt: 2024,
    featured: false,
    address: "Hay Riad, Rabat — localisation illustrative",
    latitude: 33.9619,
    longitude: -6.8596,
    amenityIds: [amenities.airConditioning, amenities.homeAutomation, amenities.fitnessRoom, amenities.security],
    imageUrls: ["/sample-listings/rabat-hassan.jpg"],
    title: "Annonce exemple — Duplex avec terrasse à Hay Riad",
    titleEn: "Sample listing — Duplex with terrace in Hay Riad",
    titleAr: "عقار نموذجي — دوبلكس مع شرفة في حي الرياض",
    description: "Duplex de location imaginé pour présenter l’expérience de recherche Domify à Rabat, avec quatre chambres et une terrasse panoramique. Cette annonce est un exemple fonctionnel : le loyer, le lieu et les photos ne correspondent pas à une disponibilité réelle.",
    descriptionEn: "A rental duplex created to present Domify’s Rabat search experience, with four bedrooms and a panoramic terrace. This listing is a functional example: rent, location, and photos do not represent real availability.",
    descriptionAr: "دوبلكس للإيجار صُمم لعرض تجربة البحث في دوميفاي بالرباط، مع أربع غرف نوم وشرفة بانورامية. هذا الإعلان مثال وظيفي، والإيجار والموقع والصور لا تمثل توفرًا حقيقيًا.",
    seoTitle: "Annonce exemple — Duplex à Hay Riad, Rabat | Domify",
    seoTitleEn: "Sample listing — Duplex in Hay Riad, Rabat | Domify",
    seoTitleAr: "عقار نموذجي — دوبلكس في حي الرياض، الرباط | دوميفاي",
    seoDescription: "Annonce exemple Domify : duplex illustratif à Hay Riad. Loyer et emplacement sont fictifs et non disponibles à la location.",
    seoDescriptionEn: "Domify sample listing: illustrative Hay Riad duplex. Rent and location are fictional and unavailable for rental.",
    seoDescriptionAr: "عقار نموذجي من دوميفاي: دوبلكس توضيحي في حي الرياض. الإيجار والموقع افتراضيان وغير متاحين للإيجار.",
  },
  {
    reference: "DEMO-MAR-001",
    slug: "demo-riad-patio-medina-marrakech",
    city: "Marrakech",
    cityId: "cmscgdgtw000gucvitsv0kh5i",
    propertyType: "Riad",
    propertyTypeId: "cmscgdb6r0004ucviip0sba3c",
    listingType: "VENTE",
    status: "PUBLISHED",
    price: 4950000,
    surfaceArea: 310,
    bedrooms: 5,
    bathrooms: 5,
    floors: 2,
    yearBuilt: 1930,
    featured: false,
    address: "Médina, Marrakech — localisation illustrative",
    latitude: 31.6295,
    longitude: -7.9811,
    amenityIds: [amenities.airConditioning, amenities.homeAutomation, amenities.swimmingPool, amenities.security],
    imageUrls: ["/sample-listings/marrakech-riad.jpg"],
    title: "Annonce exemple — Riad avec patio dans la Médina",
    titleEn: "Sample listing — Riad with patio in the Medina",
    titleAr: "عقار نموذجي — رياض بفناء في المدينة القديمة",
    description: "Riad de démonstration inspiré de l’architecture de la Médina de Marrakech, composé de cinq suites, d’un patio arboré et d’un bassin. Cette fiche est illustrative : les photos, le prix, l’adresse et la disponibilité ne décrivent pas un riad réellement en vente.",
    descriptionEn: "A demonstration riad inspired by Marrakech Medina architecture, with five suites, a planted patio, and a plunge pool. This page is illustrative: photos, price, address, and availability do not describe a riad actually for sale.",
    descriptionAr: "رياض نموذجي مستوحى من عمارة المدينة القديمة في مراكش، يضم خمس غرف وفناءً مزروعاً وحوضاً صغيراً. هذه الصفحة توضيحية، والصور والسعر والعنوان والتوفر لا تصف رياضاً معروضاً للبيع فعلياً.",
    seoTitle: "Annonce exemple — Riad dans la Médina de Marrakech | Domify",
    seoTitleEn: "Sample listing — Riad in Marrakech Medina | Domify",
    seoTitleAr: "عقار نموذجي — رياض في مدينة مراكش القديمة | دوميفاي",
    seoDescription: "Annonce exemple Domify : riad illustratif dans la Médina de Marrakech. Aucun élément affiché ne constitue une offre réelle.",
    seoDescriptionEn: "Domify sample listing: illustrative Marrakech Medina riad. No displayed item constitutes a real offer.",
    seoDescriptionAr: "عقار نموذجي من دوميفاي: رياض توضيحي في مدينة مراكش القديمة. لا تشكل أي معلومة معروضة عرضاً حقيقياً.",
  },
  {
    reference: "DEMO-MAR-002",
    slug: "demo-location-appartement-hivernage-marrakech",
    city: "Marrakech",
    cityId: "cmscgdgtw000gucvitsv0kh5i",
    propertyType: "Appartement",
    propertyTypeId: "cmscgd9dc0000ucvip12rahjw",
    listingType: "LOCATION",
    status: "PUBLISHED",
    price: 15000,
    surfaceArea: 112,
    bedrooms: 2,
    bathrooms: 2,
    floors: 5,
    yearBuilt: 2022,
    featured: false,
    address: "Hivernage, Marrakech — localisation illustrative",
    latitude: 31.6252,
    longitude: -8.0129,
    amenityIds: [amenities.airConditioning, amenities.homeAutomation, amenities.swimmingPool, amenities.security],
    imageUrls: ["/sample-listings/marrakech-apartment.jpg"],
    title: "Annonce exemple — Appartement terrasse à l’Hivernage",
    titleEn: "Sample listing — Terrace apartment in Hivernage",
    titleAr: "عقار نموذجي — شقة بشرفة في الحي الشتوي",
    description: "Appartement de démonstration à Marrakech pensé pour illustrer un séjour résidentiel contemporain, avec deux chambres, terrasse et piscine de résidence. Cette annonce ne concerne aucun logement disponible ; son prix et son emplacement sont purement indicatifs.",
    descriptionEn: "A Marrakech demonstration apartment intended to illustrate contemporary residential living, with two bedrooms, terrace, and a residence pool. This listing concerns no available home; its price and location are purely indicative.",
    descriptionAr: "شقة نموذجية في مراكش لعرض أسلوب السكن المعاصر، تضم غرفتين وشرفة ومسبحاً في الإقامة. لا يتعلق هذا الإعلان بأي سكن متاح، والسعر والموقع إرشاديان فقط.",
    seoTitle: "Annonce exemple — Location à l’Hivernage, Marrakech | Domify",
    seoTitleEn: "Sample listing — Rental in Hivernage, Marrakech | Domify",
    seoTitleAr: "عقار نموذجي — إيجار في الحي الشتوي، مراكش | دوميفاي",
    seoDescription: "Annonce exemple Domify : location illustrative à l’Hivernage. Le logement, le loyer et la localisation ne sont pas réels.",
    seoDescriptionEn: "Domify sample listing: illustrative Hivernage rental. The home, rent, and location are not real.",
    seoDescriptionAr: "عقار نموذجي من دوميفاي: إيجار توضيحي في الحي الشتوي. السكن والإيجار والموقع غير حقيقية.",
  },
  {
    reference: "DEMO-TNG-001",
    slug: "demo-appartement-vue-baie-tanger",
    city: "Tanger",
    cityId: "cmscgdha4000hucvigch0ld4s",
    propertyType: "Appartement",
    propertyTypeId: "cmscgd9dc0000ucvip12rahjw",
    listingType: "VENTE",
    status: "PUBLISHED",
    price: 3250000,
    surfaceArea: 136,
    bedrooms: 3,
    bathrooms: 2,
    floors: 8,
    yearBuilt: 2023,
    featured: true,
    address: "Malabata, Tanger — localisation illustrative",
    latitude: 35.7721,
    longitude: -5.7826,
    amenityIds: [amenities.airConditioning, amenities.homeAutomation, amenities.fitnessRoom, amenities.security, amenities.seaView],
    imageUrls: ["/sample-listings/tangier-bay.jpg"],
    title: "Annonce exemple — Appartement avec vue baie à Tanger",
    titleEn: "Sample listing — Bay-view apartment in Tangier",
    titleAr: "عقار نموذجي — شقة بإطلالة على خليج طنجة",
    description: "Appartement avec vue sur la baie conçu pour illustrer la découverte immobilière à Tanger, avec trois chambres, terrasse et prestations de résidence. L’annonce est un exemple : le bien, le tarif, les images et les coordonnées ne sont pas une offre de vente.",
    descriptionEn: "A bay-view apartment designed to illustrate property discovery in Tangier, with three bedrooms, terrace, and residence services. The listing is an example: the home, price, imagery, and coordinates are not a sale offer.",
    descriptionAr: "شقة بإطلالة على الخليج صُممت لعرض استكشاف العقارات في طنجة، مع ثلاث غرف نوم وشرفة وخدمات إقامة. الإعلان مثال توضيحي، والعقار والسعر والصور والإحداثيات ليست عرض بيع.",
    seoTitle: "Annonce exemple — Appartement à Tanger | Domify",
    seoTitleEn: "Sample listing — Apartment in Tangier | Domify",
    seoTitleAr: "عقار نموذجي — شقة في طنجة | دوميفاي",
    seoDescription: "Annonce exemple Domify : appartement illustratif à Tanger. Prix, photos, vue et localisation sont fictifs et non contractuels.",
    seoDescriptionEn: "Domify sample listing: illustrative Tangier apartment. Price, photos, view, and location are fictional and non-contractual.",
    seoDescriptionAr: "عقار نموذجي من دوميفاي: شقة توضيحية في طنجة. السعر والصور والإطلالة والموقع افتراضية وغير تعاقدية.",
  },
  {
    reference: "DEMO-TNG-002",
    slug: "demo-riad-kasbah-tanger",
    city: "Tanger",
    cityId: "cmscgdha4000hucvigch0ld4s",
    propertyType: "Riad",
    propertyTypeId: "cmscgdb6r0004ucviip0sba3c",
    listingType: "VENTE",
    status: "PUBLISHED",
    price: 3980000,
    surfaceArea: 280,
    bedrooms: 4,
    bathrooms: 4,
    floors: 3,
    yearBuilt: 1910,
    featured: false,
    address: "Kasbah, Tanger — localisation illustrative",
    latitude: 35.7883,
    longitude: -5.819,
    amenityIds: [amenities.airConditioning, amenities.homeAutomation, amenities.security, amenities.seaView],
    imageUrls: ["/sample-listings/tangier-coast.jpg"],
    title: "Annonce exemple — Riad panoramique dans la Kasbah",
    titleEn: "Sample listing — Panoramic riad in the Kasbah",
    titleAr: "عقار نموذجي — رياض بانورامي في القصبة",
    description: "Riad panoramique de démonstration évoquant les ruelles historiques de la Kasbah de Tanger, avec quatre suites et terrasse ouverte. Il sert uniquement à illustrer les fonctionnalités de Domify ; ses détails, photos, prix et localisation sont fictifs.",
    descriptionEn: "A panoramic demonstration riad evoking Tangier Kasbah’s historic lanes, with four suites and an open terrace. It exists only to illustrate Domify functionality; its details, photos, price, and location are fictional.",
    descriptionAr: "رياض بانورامي نموذجي يستحضر أزقة قصبة طنجة التاريخية، مع أربع غرف وشرفة مفتوحة. يوجد فقط لعرض وظائف دوميفاي، وجميع تفاصيله وصوره وسعره وموقعه افتراضية.",
    seoTitle: "Annonce exemple — Riad dans la Kasbah de Tanger | Domify",
    seoTitleEn: "Sample listing — Riad in Tangier Kasbah | Domify",
    seoTitleAr: "عقار نموذجي — رياض في قصبة طنجة | دوميفاي",
    seoDescription: "Annonce exemple Domify : riad illustratif à Tanger. Les informations et photos ne représentent pas un bien réellement à vendre.",
    seoDescriptionEn: "Domify sample listing: illustrative Tangier riad. Information and photos do not represent a property actually for sale.",
    seoDescriptionAr: "عقار نموذجي من دوميفاي: رياض توضيحي في طنجة. المعلومات والصور لا تمثل عقاراً معروضاً للبيع فعلياً.",
  },
  {
    reference: "DEMO-AGA-001",
    slug: "demo-appartement-vue-panorama-agadir",
    city: "Agadir",
    cityId: "cmscgdi6j000jucviga1dj2kp",
    propertyType: "Appartement",
    propertyTypeId: "cmscgd9dc0000ucvip12rahjw",
    listingType: "VENTE",
    status: "PUBLISHED",
    price: 2150000,
    surfaceArea: 128,
    bedrooms: 3,
    bathrooms: 2,
    floors: 7,
    yearBuilt: 2024,
    featured: false,
    address: "Founty, Agadir — localisation illustrative",
    latitude: 30.4194,
    longitude: -9.5991,
    amenityIds: [amenities.airConditioning, amenities.homeAutomation, amenities.fitnessRoom, amenities.security, amenities.seaView],
    imageUrls: ["/sample-listings/tangier-panoramic.jpg"],
    title: "Annonce exemple — Appartement panoramique à Agadir",
    titleEn: "Sample listing — Panoramic apartment in Agadir",
    titleAr: "عقار نموذجي — شقة بانورامية في أكادير",
    description: "Appartement panoramique préparé pour démontrer la navigation par carte et les filtres Domify à Agadir, avec séjour ouvert et trois chambres. Les éléments de cette page sont des données d’exemple et ne décrivent ni une adresse précise ni une propriété disponible.",
    descriptionEn: "A panoramic apartment prepared to demonstrate Domify map navigation and Agadir filters, with open living and three bedrooms. The elements on this page are sample data and do not describe either a precise address or an available property.",
    descriptionAr: "شقة بانورامية أُعدت لعرض تصفح الخريطة وفلاتر دوميفاي في أكادير، مع مساحة معيشة مفتوحة وثلاث غرف نوم. عناصر هذه الصفحة بيانات نموذجية ولا تصف عنواناً دقيقاً أو عقاراً متاحاً.",
    seoTitle: "Annonce exemple — Appartement à Agadir | Domify",
    seoTitleEn: "Sample listing — Apartment in Agadir | Domify",
    seoTitleAr: "عقار نموذجي — شقة في أكادير | دوميفاي",
    seoDescription: "Annonce exemple Domify : appartement illustratif à Agadir. Les caractéristiques, le prix et la localisation sont indicatifs uniquement.",
    seoDescriptionEn: "Domify sample listing: illustrative Agadir apartment. Features, price, and location are indicative only.",
    seoDescriptionAr: "عقار نموذجي من دوميفاي: شقة توضيحية في أكادير. المواصفات والسعر والموقع إرشادية فقط.",
  },
  {
    reference: "DEMO-AGA-002",
    slug: "demo-villa-location-marina-agadir",
    city: "Agadir",
    cityId: "cmscgdi6j000jucviga1dj2kp",
    propertyType: "Villa",
    propertyTypeId: "cmscgd9tz0001ucvizi1yanz5",
    listingType: "LOCATION",
    status: "PUBLISHED",
    price: 28000,
    surfaceArea: 365,
    bedrooms: 4,
    bathrooms: 4,
    floors: 2,
    yearBuilt: 2021,
    featured: false,
    address: "Marina, Agadir — localisation illustrative",
    latitude: 30.4212,
    longitude: -9.6105,
    amenityIds: [amenities.airConditioning, amenities.twoCarGarage, amenities.privateGarden, amenities.swimmingPool, amenities.security],
    imageUrls: ["/sample-listings/rabat-medina.jpg"],
    title: "Annonce exemple — Villa de location près de la Marina",
    titleEn: "Sample listing — Rental villa near the Marina",
    titleAr: "عقار نموذجي — فيلا للإيجار قرب المارينا",
    description: "Villa de location de démonstration imaginée pour illustrer une recherche familiale près de la Marina d’Agadir, avec jardin, piscine et quatre chambres. Cette fiche n’est pas une annonce réelle : le loyer, les visuels et la localisation restent strictement illustratifs.",
    descriptionEn: "A demonstration rental villa imagined to illustrate a family search near Agadir Marina, with garden, pool, and four bedrooms. This page is not a real listing: rent, imagery, and location remain strictly illustrative.",
    descriptionAr: "فيلا إيجار نموذجية لتوضيح بحث عائلي قرب مارينا أكادير، مع حديقة ومسبح وأربع غرف نوم. هذه الصفحة ليست إعلاناً حقيقياً، والإيجار والصور والموقع إرشادية حصراً.",
    seoTitle: "Annonce exemple — Villa en location à Agadir | Domify",
    seoTitleEn: "Sample listing — Rental villa in Agadir | Domify",
    seoTitleAr: "عقار نموذجي — فيلا للإيجار في أكادير | دوميفاي",
    seoDescription: "Annonce exemple Domify : villa de location illustrative à Agadir. Aucun élément n’est une disponibilité ou un tarif réel.",
    seoDescriptionEn: "Domify sample listing: illustrative Agadir rental villa. No element is a real availability or rate.",
    seoDescriptionAr: "عقار نموذجي من دوميفاي: فيلا إيجار توضيحية في أكادير. لا يمثل أي عنصر توفراً أو سعراً حقيقياً.",
  },
];
